module.exports = [
  {
    name: `The Alamagoozlum Cocktail`,
    directions: `0.5 egg white, 2.0 ounces genever gin, 2.0 ounces water, 1.5 ounces Jamaican rum, 1.5 ounces yellow or green Chartreuse, 1.5 ounces gomme syrup, 0.5 ounce orange curaçao, 0.5 ounce Angostura bitters`,
    tagIds: [2, 3, 8, 18],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/01/alamagoozlum.jpg`,
  },
  {
    name: `The Algonquin Cocktail`,
    directions: `1.50 ounces rye, 0.75 ounce dry vermouth, 0.75 ounce pineapple juice`,
    tagIds: [7, 12],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/08/algonquin.jpg`,
  },
  {
    name: `The Amarosa Cocktail`,
    directions: `1.0 ounce Amaro Cora, 1.0 ounce gin, 1.0 ounce kirschwasser, 2.0 ounces Amaro Cora, 0.5 ounce gin, 0.5 ounce kirschwasser`,
    tagIds: [2, 16],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/11/amarosa.jpg`,
  },
  {
    name: `Arnaud’s Special Cocktail`,
    directions: `2 ounces Scotch, 1 ounce Dubonnet Rouge, 3 dashes oranges bitters`,
    tagIds: [1, 9, 13],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/12/arnaud.jpg`,
  },
  {
    name: `The Avenue`,
    directions: `1 ounce bourbon, 1 ounce Calvados, 1 ounce passion fruit juice or nectar, 1 dash real pomegranate grenadine, 1 dash orange flower water`,
    tagIds: [1, 12, 17, 19, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2014/11/the-avenue.jpg`,
  },
  {
    name: `The Aviation`,
    directions: `2.50 ounces gin, 0.75 ounce fresh lemon juice, 2 or 3 dashes maraschino liqueur, 2.00 ounces gin, 0.75 ounce fresh lemon juice, 0.50 ounce maraschino liqueur, 0.25 ounce Crème de violette or Crème Yvette`,
    tagIds: [2, 7, 11, 12, 14, 18, 19, 21],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/03/aviation.jpg`,
  },
  {
    name: `Barbara West Cocktail`,
    directions: `2.0 ounces gin, 1.0 ounce sherry, 0.5 ounce lemon juice, 1 small dash Angostura bitters`,
    tagIds: [2, 7, 11],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/01/barbarawest.jpg`,
  },
  {
    name: `Barnum (Was Right) Cocktail`,
    directions: `2.0 ounces gin, 1.0 ounce apricot-flavored brandy (the best is Marie Brizard’s Apry), 0.5 ounce fresh lemon juice, 2 dashes Angostura bitters`,
    tagIds: [2, 11, 12, 13],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/08/barnum.jpg`,
  },
  {
    name: `The Bebbo Cocktail`,
    directions: `1.5 ounces gin, 1.0 ounce fresh lemon juice, 0.5 ounce honey, 2.0 teaspoons orange juice`,
    tagIds: [2, 11, 12, 18],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/01/bebbo.jpg`,
  },
  {
    name: `The Blackthorn Cocktail`,
    directions: `2.00 ounces gin, 0.75 ounce Dubonnet Rouge, 0.75 ounce kirschwasser`,
    tagIds: [2, 13, 15],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/12/blackthorn.jpg`,
  },
  {
    name: `The Blinker`,
    directions: `2.0 ounces rye (Old Overholt specified by Dr. Cocktail), 1.0 ounce grapefruit juice, 2 bar spoons (1 teaspoon) raspberry syrup`,
    tagIds: [11, 12, 17, 18, 21],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/01/theblinker.jpg`,
  },
  {
    name: `Blood and Sand`,
    directions: `1.00 ounce Scotch, 1.00 ounce orange juice, 0.75 ounce cherry-flavored brandy, 0.75 ounce sweet vermouth`,
    tagIds: [1, 9, 12, 17],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/01/bloodandsand.jpg`,
  },
  {
    name: `The Blue Moon`,
    directions: `2.0 ounces gin, 0.5 ounce Crème Yvette or crème de violette, 0.5 ounce lemon juice`,
    tagIds: [2, 11, 12, 17, 19],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/01/bluemoon.jpg`,
  },
  {
    name: `Blue Paradise`,
    directions: `2 ounces cognac, 1 ounce Dubonnet Rouge, 4 dashes Parfait Amour`,
    tagIds: [13],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/12/blueparadise.jpg`,
  },
  {
    name: `The Boulevardier`,
    directions: `1.5 ounce bourbon, 1 ounce Campari, 1 ounce sweet vermouth`,
    tagIds: [1, 13, 14, 16, 21],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2014/11/boulevardier.jpg`,
  },
  {
    name: `The Brandy Crusta`,
    directions: `1 lemon, 0.5 teaspoon fresh lemon juice, Bar or table sugar, 2.0 ounces cognac (Hennessy specified), 1 teaspoon orange curaçao (Marie Brizard specified), 1 dash Boker’s Bitters (or substitute Angostura)`,
    tagIds: [12, 17],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/02/brandycrusta.jpg`,
  },
  {
    name: `The Brooklyn Cocktail`,
    directions: `2.00 ounces rye or bourbon, 0.75 ounce dry vermouth, 1/4 ounce Amer Picon, 1/4 ounce maraschino liqueur`,
    tagIds: [1, 7, 13, 14, 21],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/03/brooklyn.jpg`,
  },
  {
    name: `The Calvados Cocktail`,
    directions: `1.50 ounces Calvados, 1.50 ounce orange juice, 0.75 ounce Cointreau, 0.75 ounce orange bitters`,
    tagIds: [16, 17],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/02/calvadoscocktail.jpg`,
  },
  {
    name: `Chatham Hotel Special`,
    directions: `1.5 ounces brandy, 0.5 ounce ruby port, 0.5 cream, 1 dash dark creme de cacao`,
    tagIds: [12, 24, 25],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/02/chathamhotel.jpg`,
  },
  {
    name: `The Coffee Cocktail`,
    directions: `1 ounce brandy (Martell works well), 1 egg, 2 to 3 ounces ruby port, 1 teaspoon sugar`,
    tagIds: [12, 24],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/02/coffeecocktail.jpg`,
  },
  {
    name: `The Communist`,
    directions: `1.00 ounce gin, 1.00 ounce orange juice, 0.50 ounce cherry brandy (Cherry Heering), 0.75 ounce fresh lemon juice`,
    tagIds: [2, 11, 17],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/09/communist.jpg`,
  },
  {
    name: `The Corpse Reviver #2`,
    directions: `1 ounce gin, 1 ounce Cointreau, 1 ounce Lillet Blanc, 1 ounce fresh lemon juice, 1 to 3 drops (not dashes) of absinthe or pastis`,
    tagIds: [2, 8, 11, 16, 19],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2014/11/reviver.jpg`,
  },
  {
    name: `Crimean Cup à la Marmora`,
    directions: `2.0 broad slices of lemon peel, 1.0 teaspoon sugar, 0.5 ounce dark Jamaican rum (Myers’s works well), 1.0 ounce brandy, 0.5 maraschino liqueur, 0.5 ounce Jamaican rum, 2.0 ounces orgeat syrup, 0.5 lemon juice, 4.0 ounces soda water, 3.0 ounces chilled champagne`,
    tagIds: [3, 6, 11, 12, 15, 17, 18, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/01/crimean.jpg`,
  },
  {
    name: `Curaçao Punch`,
    directions: `0.5 tablespoon sugar (alter to taste), 2 or 3 dashes of fresh lemon juice, 1.0 ounce soda water, 1.0 ounce brandy (Martell cognac specified), 2.0 ounces orange curaçao, 1.0 ounce Jamaican rum (full-bodied specified)`,
    tagIds: [3, 6, 11, 12, 15, 17, 18, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/02/curacaopunch.jpg`,
  },
  {
    name: `The Delicious Sour`,
    directions: `2.0 ounces applejack, 2.0 ounces peach flavored brandy, juice of one fresh lime (1 to 1.5 ounces), 1 egg white, 1 teaspoon sugar, soda water`,
    tagIds: [6, 8, 11, 12, 17, 18],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/02/delicioussour.jpg`,
  },
  {
    name: `The Derby`,
    directions: `1.00 ounce bourbon, 0.50 ounce sweet vermouth, 0.50 ounce orange curaçao, 0.75 ounce fresh lime juice`,
    tagIds: [1, 11, 13],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/06/derby.jpg`,
  },
  {
    name: `Diki-Diki Cocktail`,
    directions: `1.50 ounces Calvados, 0.50 ounce Swedish Punsch, 0.75 ounce grapefruit juice`,
    tagIds: [11, 12, 15, 17],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/11/dikidiki.jpg`,
  },
  {
    name: `Doctor Cocktail`,
    directions: `2 ounces Jamaican rum, 1 ounce Swedish Punsch, 1 ounce fresh lime juice`,
    tagIds: [3, 11, 12, 15, 17],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/12/doctorcocktail.jpg`,
  },
  {
    name: `East India Cocktail`,
    directions: `3.0 ounces brandy, 0.5 ounces raspberry syrup, one dash Angostura bitters, one teaspoon orange curaçao, one teaspoon maraschino liqueur`,
    tagIds: [12, 15, 17, 19],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/01/eastindiacocktail.jpg`,
  },
  {
    name: `Fairbank Cocktail`,
    directions: `1.75 ounces gin, 0.75 ounce dry vermouth, 2 dashes orange bitters (Regan’s #6 recommended), 2 dashes crème de noyeaux`,
    tagIds: [2, 7, 19, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/08/fairbank.jpg`,
  },
  {
    name: `The Filmograph Cocktail`,
    directions: `2.00 ounces brandy, 0.75 ounce lemon syrup (substitute fresh lemon juice unless you like to drink maple syrup out of the can.), 0.50 ounce kola tonic`,
    tagIds: [6, 12, 15, 19, 25],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/10/filmograph.jpg`,
  },
  {
    name: `Fish House Punch`,
    directions: `2.0 quarts Jamaican Rum (Appleton recommended), 1.0 quart brandy (Hennessy recommended), 0.5 pint peach brandy, 0.5 pint maraschino liquor, 1.0 quart freshly made green tea, 1.0 pint lemon juice, 1.0 pound powdered (not confectioners’) sugar, 1.0 bottle champagne`,
    tagIds: [3, 6, 11, 12, 15, 17, 19],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/07/fishhouse1.jpg`,
  },
  {
    name: `The Flying Dutchman`,
    directions: `2 ounces orange gin, Juice of ¼ orange, Juice of ¼ lime, 3 drops Angostura bitters`,
    tagIds: [2, 12, 17, 19],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/09/flyingdutchman.jpg`,
  },
  {
    name: `The Fogcutter`,
    directions: `1 lemon, 0.5 teaspoon fresh lemon juice, Bar or table sugar, 2.0 ounces cognac (Hennessy specified), 1 teaspoon orange curaçao (Marie Brizard specified), 1 dash Boker’s Bitters (or substitute Angostura)`,
    tagIds: [11, 12, 19],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2014/12/fogcutter.jpg`,
  },
  {
    name: `Fogcutter (Early)`,
    directions: `2.0 ounces Barcardi Gold rum, 0.5 ounce Plymouth Gin, 1.0 ounce Pisco Brandy, 1.0 ounce orange juice, 2.0 ounces lemon juice, 0.5 ounce orgeat syrup, 0.5 ounce cream sherry`,
    tagIds: [2, 3, 11, 12, 17, 24],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2014/12/fogcutterearly.jpg`,
  },
  {
    name: `The Ford Cocktail`,
    directions: `1 ounce Old Tom Gin (Hayman’s Old Tom Gin recommended), 1 ounce dry vermouth, 3 dashes Bénédictine, 3 dashes orange bitters`,
    tagIds: [2, 7, 13, 20],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/09/ford.jpg`,
  },
  {
    name: `The Fred Collins Fiz`,
    directions: `2.0 ounces bourbon or rye whiskey, 0.5 ounce simple syrup, Juice of one lemon, 1 teaspoon orange curaçao, 6.0 ounces lemonade`,
    tagIds: [1, 6, 11, 12],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/11/fredcollinsfiz.jpg`,
  },
  {
    name: `The French 75`,
    directions: `2 ounces gin, 1 ounce lemon juice, 2 teaspoons sugar or 1 teaspoon simple syrup, champagne`,
    tagIds: [2, 6, 11, 12, 18],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/01/french75.jpg`,
  },
  {
    name: `The Georgia Mint Julep`,
    directions: `fresh mint leaves, 1 teaspoon sugar, A dash of water, 2 ounces cognac (or other brandy), 1 ounce real peach brandy`,
    tagIds: [12, 17],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/05/georgiamintjulep.jpg`,
  },
  {
    name: `Golden Dawn`,
    directions: `0.75 ounce (or 1.0 ounces) Calvados, 0.75 ounce (or 1.0 ounces) dry gin, 0.75 ounce (or 0.5 ounce) apricot brandy (Marie Brizard Apry), 0.75 ounce (or 0.5 ounce) orange juice, Pomegranate grenadine`,
    tagIds: [2, 7, 12, 17, 19],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/02/goldendawn.jpg`,
  },
  {
    name: `Hanky Panky`,
    directions: `1.5 ounces gin, 1.5 ounces sweet vermouth, 2 dashes Fernet Branca`,
    tagIds: [2, 7, 12, 13],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2014/12/hankypanky.jpg`,
  },
  {
    name: `Have a Heart Cocktail`,
    directions: `1.50 ounces gin, 0.75 ounce Swedish Punsch, 0.75 ounce fresh lime juice, 0.25 ounce real pomegranate grenadine`,
    tagIds: [2, 15, 17, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2014/12/haveaheart.jpg`,
  },
  {
    name: `Honeymoon Cocktail`,
    directions: `2.0 ounces Calvados, 0.5 ounce Bénédictine, 0.5 ounce orange curaçao, 0.5 ounce lemon juice`,
    tagIds: [7, 11, 17, 20],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/02/honeymoon.jpg`,
  },
  {
    name: `The Income Tax Cocktail`,
    directions: `1.50 ounces gin, 0.75 ounce dry vermouth, 0.75 ounce sweet vermouth, Juice of 1/4 orange (squeezed right in the shaker), 2 dashes Angostura Bitters`,
    tagIds: [2, 7, 12, 14, 18, 21],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/04/incometax.jpg`,
  },
  {
    name: `The Jack Rose Cocktail`,
    directions: `1.5 ounces applejack, Juice of 1/2 lime (or lemon – about one ounce), 2 or more dashes of real pomegranate grenadine`,
    tagIds: [11, 12, 17],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2014/11/jackrose.jpg`,
  },
  {
    name: `The Japalac Cocktail`,
    directions: `Juice of 1/4 orange, 0.75 ounce dry vermouth, 0.75 ounce rye whiskey, 1 teaspoon raspberry syrup`,
    tagIds: [1, 7, 9, 15, 17, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/02/japalac.jpg`,
  },
  {
    name: `Jasper’s Jamaican Planter’s Punch`,
    directions: `1.5 ounces dark Jamaican rum (Coruba), 1.5 ounces Jasper’s Secret Mix`,
    tagIds: [3, 15, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/09/jaspersplanters.jpg`,
  },
  {
    name: `The Jupiter Cocktail`,
    directions: `1.50 ounces gin, 0.75 ounce dry vermouth, 1 teaspoon Parfait Amour, 1 teaspoon orange juice`,
    tagIds: [2, 7, 12, 15, 17],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/04/jupiter.jpg`,
  },
  {
    name: `Knickerbocker à la Monsieur`,
    directions: `2.0 ounces Virgin Islands rum, 0.5 ounces orange curaçao, 0.5 ounce raspberry syrup, 1.0 ounce lemon juice, 1 slice orange, 1 slice pineapple`,
    tagIds: [2, 3, 12, 15, 17, 19, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/02/knickerbocker.jpg`,
  },
  {
    name: `La Floridita Daiquiri`,
    directions: `2 ounces rum (such as Havana Club from Cuba or Brugal from the Dominican Republic), Juice of 1/2 lime (If your limes are small, use the whole thing), 1 teaspoon sugar or sugar syrup (increase if too tart), 1 teaspoon maraschino liqueur`,
    tagIds: [3, 11, 12, 15, 17, 18],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/09/floridita.jpg`,
  },
  {
    name: `Leatherneck Cocktail`,
    directions: `2.00 ounces blended whiskey (Crown Royal recommended), 0.75 ounce blue curaçao, 0.50 ounce fresh lime juice`,
    tagIds: [1, 12, 15, 17, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/09/leatherneck.jpg`,
  },
  {
    name: `The Liberal`,
    directions: `0.75 ounce 100-proof Wild Turkey, 0.75 ounce Italian vermouth (Carpano Antica), 3 dashes Torani Amer, 1 generous dash orange bitters`,
    tagIds: [7, 12, 19],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/08/theliberal.jpg`,
  },
  {
    name: `The Lion’s Tail`,
    directions: `2.00 ounces bourbon, 0.75 ounce Allspice Dram (or less, to taste), 0.50 ounce fresh lime juice, 0.50 tablespoon simple syrup (or less, to taste), 2 dashes Angostura Bitters`,
    tagIds: [1, 11, 12, 15, 20],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/05/lionstail.jpg`,
  },
  {
    name: `Lucien Gaudin Cocktail`,
    directions: `1.0 ounce gin, 0.5 ounce Cointreau, 0.5 ounce Campari, 0.5 ounce dry vermouth`,
    tagIds: [2, 7, 13, 16, 19],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2014/11/luciengaudin.jpg`,
  },
  {
    name: `Mamie Taylor`,
    directions: `2 ounces Scotch, 3/4 ounce fresh lime juice, Spicy ginger ale or ginger beer (Blenheim’s #3 ginger ale recommended)`,
    tagIds: [1, 6, 9, 11],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/12/mamietaylor.jpg`,
  },
  {
    name: `Milk Punch`,
    directions: `1.0 ounce brandy, 0.5 ounce dark rum, 2 teaspoons simple syrup, 2 dashes vanilla extract, 4.0 ounces whole milk`,
    tagIds: [3, 12, 19, 24, 25],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/01/milkpunch.jpg`,
  },
  {
    name: `The Millionaire`,
    directions: `1.50 ounces Myers’s Original Dark Rum, 0.75 ounce sloe gin, 0.75 ounce apricot brandy, juice of one fresh lime (1 to 1.5 ounces)`,
    tagIds: [2, 3, 11, 12, 17, 19],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/02/themillionaire.jpg`,
  },
  {
    name: `The Modernista`,
    directions: `2.0 ounces Scotch, 0.5 ounce dark Jamaican rum, 1 teaspoon absinthe or pastis (Pernod, Herbsaint and Ricard all work.), 0.5 ounce Swedish Punsch, 0.5 ounce fresh lemon juice, 2 dashes orange bitters`,
    tagIds: [1, 3, 9, 11, 12, 15, 19, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/09/modernista.jpg`,
  },
  {
    name: `The Monkey Gland`,
    directions: `1.5 ounces dry gin, 1.5 ounces orange juice, 1 teaspoon pomegranate grenadine, 1 teaspoon absinthe or pastis`,
    tagIds: [2, 7, 12, 17, 19, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/02/monkeygland.jpg`,
  },
  {
    name: `The Moscow Mule`,
    directions: `2 ounces vodka, Juice of 1/2 lime, Ginger beer or ginger ale`,
    tagIds: [4, 6, 10, 11],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2014/12/moscowmule.jpg`,
  },
  {
    name: `The Mother-in-Law Cocktail`,
    directions: `1.0 teaspoon  Peychaud’s  bitters, 1.0 teaspoon  Angostura  bitters, 1.0 teaspoon Amer Picon (subsitute Torani Amer), 0.5 ounce orange curaçao, 0.5 maraschino liqueur, 0.5 ounce simple syrup, 0.5 ounce maraschino liqueur, 9.0 ounces bourbon, 1.0 teaspoon, 1.0 teaspoon, 1.0 teaspoon Amer Picon (subsitute Torani Amer), 0.5 ounce orange curaçao`,
    tagIds: [1, 10, 12, 16, 17, 19, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/01/mother-in-law.jpg`,
  },
  {
    name: `Palm Beach Special`,
    directions: `2.50 ounces gin, 0.75 ounce grapefruit juice, 0.50 ounce sweet vermouth`,
    tagIds: [2, 11],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2014/12/palmbeachspecial.jpg`,
  },
  {
    name: `Park Avenue Cocktail`,
    directions: `2.0 ounces gin, 0.75 ounce pineapple juice, 0.75 ounce sweet vermouth, 2 tablespoons orange curaçao`,
    tagIds: [2, 12, 17, 19],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2014/11/parkavenue.jpg`,
  },
  {
    name: `Pegu Club Cocktail`,
    directions: `1.50 ounces gin, 0.50 ounce Cointreau, 0.75 ounce fresh lime juice, 2 dashes Angostura bitters`,
    tagIds: [2, 12, 17],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/08/peguclub.jpg`,
  },
  {
    name: `The Pendennis Cocktail`,
    directions: `2 ounces gin, 1 ounce apricot (some say peach) brandy, 2-3 dashes  Peychaud’s bitters, 3/4 ounce fresh lime juice`,
    tagIds: [2, 11, 19],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/12/pendennis.jpg`,
  },
  {
    name: `Picon Punch`,
    directions: `1.0 teaspoon real pomegranate grenadine, 2.5 ounces Amer Picon, Soda Water, 1.0 ounce brandy`,
    tagIds: [6, 10, 17, 19],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/02/piconpunch.jpg`,
  },
  {
    name: `Pink Gin`,
    directions: `3 ounces Plymouth Gin, 6 goodly dashes  Angostura bitters`,
    tagIds: [2, 13, 16],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/02/pinkgin.jpg`,
  },
  {
    name: `Pink Lady`,
    directions: `1.5 ounces dry gin, 0.5 ounce applejack, Juice of 1/2 lemon, 1 egg white, 2 dashes real pomegranate grenadine, 1.50 ounces Plymouth gin, 0.50 ounce Laird’s Bonded Apple Brandy, 0.75 ounce lemon juice, 0.75 ounce simple syrup, 1 egg white, 0.25 ounce grenadine`,
    tagIds: [2, 7, 8, 11, 12, 15, 17, 19, 22, 24],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/11/secretcocktail.jpg`,
  },
  {
    name: `Ritz Sidecar`,
    directions: `5 parts very old cognac, 3 parts Cointreau, 2 parts fresh lemon juice`,
    tagIds: [11, 13],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/02/sidecar.jpg`,
  },
  {
    name: `The Rose`,
    directions: `2 ounces dry French vermouth, 1 ounce kirschwasser, 1 teaspoon raspberry syrup`,
    tagIds: [7, 12, 15, 17, 19, 20, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2014/12/rose.jpg`,
  },
  {
    name: `Royal Bermuda Yacht Club Cocktail`,
    directions: `2.00 ounces Barbados Rum, 0.75 ounce lime juice, 2 dashes Cointreau, 2 teaspoons Falernum`,
    tagIds: [3, 11, 12, 20],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/01/royalbermuda.jpg`,
  },
  {
    name: `Saint Croix Rum Fix`,
    directions: `2.0 ounce Virgin Islands Rum (Cruzan Estate Dark Rum recommended), 0.5 ounce  pineapple syrup, Juice of 1/2 lemon, 2 teaspoons sugar or simple syrup`,
    tagIds: [2, 3, 11, 12, 17],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/02/saintcroix.jpg`,
  },
  {
    name: `Satan’s Whiskers Cocktail`,
    directions: `0.5 ounce gin, 0.5 ounce dry vermouth, 0.5 ounce sweet vermouth, 0.5 ounce orange juice, 2 teaspoons orange curaçao, 1 teaspoon orange bitters`,
    tagIds: [2, 7, 11, 12, 19],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2014/12/satanswhiskers.jpg`,
  },
  {
    name: `The Scofflaw`,
    directions: `1.50 ounces rye, 1.00 ounce dry vermouth, 0.75 ounce fresh lemon juice, 0.75 ounce real pomegranate grenadine`,
    tagIds: [1, 7, 11, 12, 17],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2014/12/scofflaw.jpg`,
  },
  {
    name: `The Secret Cocktail`,
    directions: `1.5 ounces dry gin, 0.5 ounce applejack, Juice of 1/2 lemon, 1 egg white, 2 dashes real pomegranate grenadine, 1.50 ounces Plymouth gin, 0.50 ounce Laird’s Bonded Apple Brandy, 0.75 ounce lemon juice, 0.75 ounce simple syrup, 1 egg white, 0.25 ounce grenadine, 1.0 ounce bourbon (venerable Old Forester was specified), 0.5 ounce Cointreau, 7 dashes  Angostura  bitters, 7 dashes  Peychaud’s  bitters`,
    tagIds: [1, 2, 7, 8, 11, 12, 17],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/11/secretcocktail.jpg`,
  },
  {
    name: `The Seelbach Cocktail`,
    directions: `1.0 ounce bourbon (venerable Old Forester was specified), 0.5 ounce Cointreau, 7 dashes  Angostura  bitters, 7 dashes  Peychaud’s  bitters, 5.0 ounces champagne`,
    tagIds: [1, 6, 16],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/01/seelbachcocktail.jpg`,
  },
  {
    name: `Seventh Heaven`,
    directions: `1.75 ounces gin, 0.50 ounce maraschino liqueur, 0.25 ounce grapefruit juice`,
    tagIds: [2, 11, 14, 18, 21],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/02/7thheaven.jpg`,
  },
  {
    name: `The Soother`,
    directions: `1.0 ounce cognac, 1.0 ounce Jamaican rum (Coruba recommended), 0.5 ounce orange curaçao, Juice of 1/2 lemon, 1 teaspoon apple juice, 1/2 teaspoon simply syrup (or Agave Nectar)`,
    tagIds: [3, 11, 12, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/02/soother.jpg`,
  },
  {
    name: `Soyer au Champagne`,
    directions: `2 dashes maraschino liqueur, 2 dashes pineapple juice, 2 dashes orange curaçao (or Grand Marnier), 2 dashes brandy, champagne, 1 tablespoon vanilla ice cream`,
    tagIds: [6, 11, 20, 22, 24, 25],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/01/soyerauchampagne.jpg`,
  },
  {
    name: `The Straits Sling`,
    directions: `2.0 ounces gin, 0.5 ounce kirschwasser, 0.5 ounce Bénédictine, Juice of 1/2 lemon, 2 dashes orange bitters, 2 dashes Angostura bitters, soda water`,
    tagIds: [2, 6, 11, 20, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2014/11/straitssling.jpg`,
  },
  {
    name: `Three to One Cocktail`,
    directions: `1.50 ounces 100-proof gin, 0.75 ounce Marie Brizard Apry, Juice of 1/2 lime`,
    tagIds: [2, 11, 12, 15],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/02/threetoone.jpg`,
  },
  {
    name: `Twelve Mile Limit`,
    directions: `1.0 ounce white rum (Appleton White Jamaican recommended), 0.5 ounce rye whiskey, 0.5 ounce brandy (Hennessy VS recommended), 0.5 ounce grenadine, 0.5 ounce lemon juice`,
    tagIds: [1, 3, 11, 13, 19],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/04/twelvemilelimit.jpg`,
  },
  {
    name: `The Twentieth Century Cocktail`,
    directions: `1.50 ounces gin, 0.75 ounce Lillet Blanc, 0.50 ounce light créme de cacao (or a scant splash, to taste), 0.75 ounce fresh lemon juice, 1.50 ounces Beefeater London Dry gin, 0.75 ounce Cocchi Americano, 0.75 ounce Marie Brizard White Créme de Cacao, 0.75 ounce fresh lemon juice`,
    tagIds: [2, 7, 11, 15, 18, 19, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/02/20thcentury.jpg`,
  },
  {
    name: `The Vesper`,
    directions: `3.0 ounces gin, 1.0 ounce vodka, 0.5 ounce Lillet Blanc`,
    tagIds: [2, 4, 13, 14],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/02/vesper.jpg`,
  },
  {
    name: `Vieux Carré Cocktail`,
    directions: `¾ oz brandy, ¾ oz rye whiskey, ¾ oz sweet vermouth, ¼ oz Benedictine, dash Peychaud's Bitters, dash Angostura Bitters`,
    tagIds: [13, 14, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/12/vieuxcarre.jpg`,
  },
  {
    name: `Vowel Cocktail`,
    directions: `1.0 ounce Scotch, 1.0 ounce sweet vermouth, 0.5 ounce orange juice (preferably fresh squeezed), 0.5 ounce kümmel (Gilka), 1 or 2 dashes Angostura Bitters`,
    tagIds: [1, 9, 15, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/03/thevowel.jpg`,
  },
  {
    name: `The Widow’s Kiss`,
    directions: `1.50 ounces Calvados, 0.75 ounce Chartreuse (Green was meant, but yellow mellows the drink a bit), 0.75 ounce Benedictine, 2 dashes Angostura bitters`,
    tagIds: [19, 20, 22],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2016/02/widowskiss.jpg`,
  },
  {
    name: `Don the Beachcomber’s Zombie`,
    directions: `1 teaspoon brown sugar, 1 ounce fresh lemon juice, 1 ounce gold Puerto Rican rum, 1 ounce 151-proof Demerara rum (from Guyana), 1 ounce white Puerto Rican rum, 1 ounce unsweetened pineapple juice, 1 ounce fresh lime juice, 1 ounce passion fruit syrup, 1 dash Angostura Bitters`,
    tagIds: [3, 11, 12, 17, 19],
    imageurl: `https://forgottencocktails.com/wp-content/uploads/sites/2/2015/04/zombie.jpg`,
  },
  {
    name: `Adonis`,
    directions: `1½ oz. dry oloroso sherry, 1½ oz. sweet vermouth, 2 dashes orange bitters`,
    tagIds: [7, 13, 14, 16, 21],
    imageurl: ``,
  },
  {
    name: `Bad Day Bitter Martini`,
    directions: `2 ½ oz London Dry Gin, ½ oz Amaro Montenegro`,
    tagIds: [2, 7, 13, 14, 16, 21],
    imageurl: ``,
  },
  {
    name: `Bijou Cocktail`,
    directions: `1 oz gin, 1 oz Chartreuse, 1 oz sweet vermouth, dash Orange Bitters`,
    tagIds: [2, 13, 14, 19, 22],
    imageurl: ``,
  },
  {
    name: `Bourbon Milk Punch`,
    directions: `1 ½ oz Bourbon, 2 tsp. simple syrup, 2 dashes vanilla extract, 4 oz. milk or half and half`,
    tagIds: [1, 12, 21, 24, 25],
    imageurl: ``,
  },
  {
    name: `Cabaret`,
    directions: `1 oz. Gin, ¾ oz. dry vermouth, ¼ oz. Benedictine, 2 dashes of Angostura Bitters`,
    tagIds: [2, 7, 13, 20, 22],
    imageurl: ``,
  },
  {
    name: `East New York Flip`,
    directions: `¾ oz Honey, 1 Egg Yolk, ¾ oz Heavy Cream, 1 oz Bourbon, 1 oz Port, Nutmeg, Ground`,
    tagIds: [1, 12, 21, 24, 25],
    imageurl: ``,
  },
  {
    name: `Fancy Free`,
    directions: `2 oz bourbon, ½ oz Maraschino Liqueur, dash Angostura Aromatic Bitters, dash Angostura Orange Bitters`,
    tagIds: [1, 13, 21],
    imageurl: ``,
  },
  {
    name: `Grasshopper Cocktail`,
    directions: `1 oz. Crème de menthe, 1 oz. white crème de cacao, 1 oz. cream`,
    tagIds: [12, 24],
    imageurl: ``,
  },
  {
    name: `Manhattan`,
    directions: `2 oz Rye Whiskey, 3/4 oz Sweet Vermouth, Bitters, Orange Peel, Cherry`,
    tagIds: [1, 13, 14],
    imageurl: ``,
  },
  {
    name: `Nirvana Cocktail`,
    directions: `2 oz. Rye Whiskey, 1 oz. Amer Picon, ¼ oz. Maraschino, ¼ oz. Benedictine`,
    tagIds: [1, 13, 14, 20],
    imageurl: ``,
  },
  {
    name: `Old Fashioned`,
    directions: `2 oz Rye Whiskey, 2 tsp Simple Syrup, Bitters, Orange Peel`,
    tagIds: [1, 13, 14],
    imageurl: ``,
  },
  {
    name: `Red Hook`,
    directions: `2 oz. Rye Whiskey, ½ oz. Maraschino Liqueur, ½ oz. Punt E Mess`,
    tagIds: [1, 13, 14],
    imageurl: ``,
  },
  {
    name: `Upper West Side`,
    directions: `2 oz. Rye Whiskey, ½ oz. Maraschino Liqueur, ½ oz. Dry Vermouth`,
    tagIds: [1, 7, 13, 14],
    imageurl: ``,
  },
  {
    name: `Tuxedo No. 2`,
    directions: `2 oz Gin, ¾ oz Dry Vermouth, ¼ oz Maraschino, 2 dashes Orange Bitters, absinthe rinse`,
    tagIds: [2, 7, 13, 14, 19, 20],
    imageurl: ``,
  },
  {
    name: `White Russian`,
    directions: `2 oz Vodka, 1 oz Kaluha, 1 oz Cream`,
    tagIds: [4, 12, 14, 20, 21, 24],
    imageurl: ``,
  },
  {
    name: `Air Mail`,
    directions: `2 oz rum -- golden rum, ½ oz lime juice, 1 tsp honey, 5 oz Brut champagne`,
    tagIds: [3, 6, 11, 18],
    imageurl: ``,
  },
  {
    name: `Bee’s Knees`,
    directions: `2 oz gin, ¾ oz lemon juice, ¾ oz honey syrup`,
    tagIds: [2, 11, 12, 19],
    imageurl: ``,
  },
  {
    name: `Biter Cocktail`,
    directions: `1 ½ oz. Gin, ¾ oz. Lemon Juice, ¾ oz. Chartreuse, ¼ oz. simple syrup, Dash absinthe`,
    tagIds: [2, 11, 14, 18],
    imageurl: ``,
  },
  {
    name: `Captain's Blood`,
    directions: `1 ½ oz rum, ¼ oz simple syrup, ¼ oz lime juice, Dash of aromatic bitters`,
    tagIds: [3, 11, 13, 19],
    imageurl: ``,
  },
  {
    name: `Clover Club`,
    directions: `1 ½ oz. gin, ¾ oz. fresh lime juice, ½ oz Grenadine, 1 fresh egg white`,
    tagIds: [2, 8, 11, 12, 14, 21],
    imageurl: ``,
  },
  {
    name: `Daiquiri Cocktail`,
    directions: `2 oz rum, ½ oz lime juice, ¾ oz simple syrup`,
    tagIds: [3, 11, 12, 14, 21],
    imageurl: ``,
  },
  {
    name: `Daiquiri No. 3`,
    directions: `2 oz. White Rum, ½ oz. simple syrup, ½ oz. grapefruit juice, 1 tsp Maraschino Liqueur`,
    tagIds: [3, 11, 12, 18, 19, 21],
    imageurl: ``,
  },
  {
    name: `Dirty Margarita`,
    directions: `2 oz Tequila, 2 oz lime juice, 1 oz agave nectar, Club soda`,
    tagIds: [5, 6, 11, 12, 14],
    imageurl: ``,
  },
  {
    name: `Fallen Angel`,
    directions: `2 oz. dry gin, 1/2 oz. lime juice, 1 dash Angostura bitters, 2 dashes White Crème De Menthe`,
    tagIds: [2, 7, 14, 20, 22],
    imageurl: ``,
  },
  {
    name: `Gin Rickey`,
    directions: `2 oz. gin, 1 oz. Lime Juice, Club soda`,
    tagIds: [2, 6, 11, 14, 21],
    imageurl: ``,
  },
  {
    name: `La Paloma`,
    directions: `2 oz Tequila, ¾ oz lime juice, Pinch of salt, Grapefruit soda`,
    tagIds: [5, 6, 14, 18, 19, 21],
    imageurl: ``,
  },
  {
    name: `Mary Pickford`,
    directions: `1 ½ oz. Rum, 1 ½ oz. Pineapple Juice, 1 tsp Grenadine, 6 drops Maraschino`,
    tagIds: [3, 12, 17, 22],
    imageurl: ``,
  },
  {
    name: `Mint Julep`,
    directions: `1 ½ oz Bourbon, ¼ oz Simple Syrup, Large Mint Sprig`,
    tagIds: [1, 12, 13, 14, 20],
    imageurl: ``,
  },
  {
    name: `Pisco Sour Cocktail`,
    directions: `2 oz. Pisco, ¾ oz. fresh lime juice, ¾ oz. simple syrup, 1 egg white`,
    tagIds: [8, 11, 12, 15],
    imageurl: ``,
  },
  {
    name: `Prado Cocktail`,
    directions: `1 ½ oz Silver Tequila, ¾ oz Lime Juice, egg white, ½ oz Maraschino Liqueur`,
    tagIds: [5, 8, 12, 14, 22],
    imageurl: ``,
  },
  {
    name: `Rum Ramsey`,
    directions: `1 ¾ oz rum, ¼ oz bourbon, ¼ oz lime juice, ¼ TSP sugar, Dash of creole bitters`,
    tagIds: [1, 3, 11, 20],
    imageurl: ``,
  },
  {
    name: `Side Car`,
    directions: `2 oz. Brandy, 1 oz. Cointreau, ½ oz. Lemon Juice`,
    tagIds: [11, 12, 19, 21],
    imageurl: ``,
  },
  {
    name: `Tom Collins`,
    directions: `2 oz gin, ¾ oz lime juice, ½ oz simple syrup, Club soda`,
    tagIds: [2, 6, 14, 18, 21],
    imageurl: ``,
  },
  {
    name: `Whiskey Sour`,
    directions: `2 oz Bourbon Whiskey, 1 oz simple syrup, 3/4 oz lemon juice, 1 egg white`,
    tagIds: [1, 8, 11, 12, 14, 18, 19, 21],
    imageurl: ``,
  },
  {
    name: `White Lady`,
    directions: `2 oz. gin, 1 oz. Cointreau, ¾ oz. lemon juice, ¼ oz. simple syrup, Egg white, Orange peel`,
    tagIds: [2, 8, 11, 12, 19, 22],
    imageurl: ``,
  },
  {
    name: `Wonderful Wonderful`,
    directions: `2 oz Gin, 1 oz Simple Syrup, ¾ oz Lime Juice, 1 Egg White`,
    tagIds: [2, 8, 11, 12, 14, 18, 21],
    imageurl: ``,
  },
  {
    name: `Eagle’s Dream`,
    directions: `Egg white, 1½ oz gin, ½ oz Violette Liqueur, ½ oz Lemon Juice, ½ tsp sugar`,
    tagIds: [2, 8, 11, 12, 19, 21],
    imageurl: ``,
  },
  {
    name: `Gimlet`,
    directions: `1 ½ oz Gin, ¾ Lemon juice, ¾ Lime juice`,
    tagIds: [2, 11, 14, 21],
    imageurl: ``,
  },
  {
    name: `Pink Grapefruit and Mint Bourbon Punch`,
    directions: `½ cup simple syrup, 10 fresh mint sprigs, 4 cups strained fresh pink grapefruit juice, 2 ½ cups bourbon, 12 dashes angostura bitters, 8 oz club soda`,
    tagIds: [1, 6, 11, 12, 20, 21],
    imageurl: ``,
  },
  {
    name: `Ramos gin fizz`,
    directions: `Egg white, 2 oz gin, 1¼ oz Simple syrup, ½ oz Lemon juice, ½ oz Lime juice, 1 oz Cream, Dash orange flower water, Club Soda`,
    tagIds: [2, 6, 8, 11, 12, 18, 19, 22, 24, 25],
    imageurl: ``,
  },
  {
    name: `South Side`,
    directions: `10-12 mint leaves, 2 oz. Gin, ¾ oz. Lemon Juice, ¾ oz. Simple Syrup`,
    tagIds: [2, 11, 12, 20],
    imageurl: ``,
  },
  {
    name: `Violet Fizz`,
    directions: `1 ½ oz Gin, ½ oz Violette liqueur, 1 oz lemon juice, ½ tsp sugar, Club Soda`,
    tagIds: [2, 6, 18],
    imageurl: ``,
  },
  {
    name: `Voyager`,
    directions: `2 oz. Rum, ½ oz. lime Juice, ½ oz. Benedictine, ½ oz. falernum, 2 dashes angostura bitters`,
    tagIds: [3, 11, 20, 22],
    imageurl: ``,
  },
  {
    name: `Ward Eight`,
    directions: `2 oz. Rye whiskey, ½ oz. Lemon juice, ½ oz. Orange Juice, 2 tsp Grenadine`,
    tagIds: [1, 11, 12, 19, 21],
    imageurl: ``,
  },
  {
    name: `East Side Cocktail`,
    directions: `2 oz Gin, 1 oz Lime Juice, ¾ oz Simple Syrup, 2 slices of cucumber, 4 leafs of mint`,
    tagIds: [2, 11, 12, 14, 18, 20, 21],
    imageurl: ``,
  },
  {
    name: `Spicy Blackberry Margarita`,
    directions: `2 oz Tequila, 2 oz Lime Juice, 4-5 Blackberries, ½ Jalapeno (thin sliced), 1 oz Agave Nectar`,
    tagIds: [5, 10, 11, 12, 17, 18, 22],
    imageurl: ``,
  },
];
