module.exports = [
  { tag: 'Whiskey' },
  { tag: 'Gin' },
  { tag: 'Rum' },
  { tag: 'Vodka' },
  { tag: 'Tequila' },
  { tag: 'Effervescent' },
  { tag: 'Dry' },
  { tag: 'Frothy' },
  { tag: 'Smokey' },
  { tag: 'Spicy' },
  { tag: 'Tart' },
  { tag: 'Sweet' },
  { tag: 'Spirit Forward' },
  { tag: 'Classic' },
  { tag: 'Exotic' },
  { tag: 'Bitter' },
  { tag: 'Fruity' },
  { tag: 'Refreshing' },
  { tag: 'Floral' },
  { tag: 'Herbal' },
  { tag: 'Simple' },
  { tag: 'Complex' },
  { tag: 'Warm' },
  { tag: 'Silky' },
  { tag: 'Rich' },
];
